# Generated by Django 5.2.7 on 2026-01-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='life',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mfd',
        ),
    ]
