# Generated by Django 5.2.7 on 2025-11-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_description_alter_vendor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='invoice_no',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
