# Generated by Django 5.2.7 on 2025-11-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cartorderitems_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
