# Generated by Django 5.2.7 on 2026-01-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cartorderitems_color_cartorderitems_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Cart Order'},
        ),
    ]
