# Generated by Django 5.2.7 on 2026-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cartorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='original_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
