# Generated by Django 5.2.7 on 2025-11-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_deal_end_date_product_has_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deal_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
