# Generated by Django 5.2.7 on 2026-02-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_productview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='title',
            field=models.CharField(default='kushpedia', max_length=100),
        ),
    ]
