# Generated by Django 5.2.7 on 2025-11-27 18:26

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_level_category_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=200, prefix='mini', unique=True)),
                ('title', models.CharField(default='Smartphones', max_length=100)),
                ('image', models.ImageField(default='mini_subcategory.jpg', upload_to='mini_subcategory')),
            ],
            options={
                'verbose_name_plural': 'Mini Sub Categories',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Electronics', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='core.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='mini_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.minisubcategory'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=200, prefix='sub', unique=True)),
                ('title', models.CharField(default='Mobile Phones & Accessories', max_length=100)),
                ('image', models.ImageField(default='subcategory.jpg', upload_to='subcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.AddField(
            model_name='minisubcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_subcategories', to='core.subcategory'),
        ),
    ]
