# Generated by Django 5.2.7 on 2026-02-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_returnrequest_returnlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='checkout_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
