# Generated by Django 5.2.7 on 2025-11-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_minisubcategory_remove_category_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minisubcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='minisubcategory',
            unique_together={('subcategory', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'title')},
        ),
    ]
