# Generated by Django 5.2.7 on 2025-12-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_cartorder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='saved',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=12),
        ),
    ]
