# Generated by Django 5.2.7 on 2025-12-28 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cartorder_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
    ]
