# Generated by Django 5.2.7 on 2025-12-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cartorderitems_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='product_status',
        ),
    ]
