# Generated by Django 5.2.7 on 2025-12-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_order_id_transaction_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='error_category',
            field=models.CharField(blank=True, choices=[('user_error', 'User Error (e.g., wrong PIN, cancelled)'), ('balance_error', 'Balance Error'), ('limit_error', 'Limit Error'), ('system_error', 'System Error'), ('timeout_error', 'Timeout Error')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='result_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='result_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_action',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Success', 'Success'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
    ]
